os: linux
dist: bionic
language: minimal

addons:
  apt:
    packages:
      - texlive
      - texlive-xetex

script:
  - make

deploy:
  provider: releases
  api_key: $TOKEN
  file: resume.pdf
  skip-cleanup: true
  on:
    tags: true
    branch: master