os: osx
language: ruby

addons:
    homebrew:
        update: true
        casks:
            - basictex

script:
    - export PATH="$PATH:/Library/TeX/texbin/"
    - make

deploy:
    provider: releases
    api_key: $TOKEN
    file: resume.pdf
    skip-cleanup: true
    on:
        tags: false
        branch: master